CREATE TABLE IF NOT EXISTS BACKLOG
(
    ID   uuid NOT NULL,
    NAME text NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USER_STORY
(
    BACKLOG_ID uuid NOT NULL,
    NAME       text NOT NULL,
    COMPLEXITY int,
    CONSTRAINT FK_USER_STORY_BACKLOG
        FOREIGN KEY (BACKLOG_ID)
            REFERENCES BACKLOG (ID),
    CONSTRAINT UNIQ_BACKLOG_ID_NAME
        UNIQUE (BACKLOG_ID, NAME)
);

